learning_users/App1/urls.py
from django.urls import path
from App1 import views


#Template URLS!

app_name= 'App1'

urlpatterns=[
	path('login/',views.user_login,name='user_login'),
	path('register/',views.register,name='register'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from App1 import views

urlpatterns = [
	path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('App1/',include('App1.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

learning_users/App1/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):

	user= models.OneToOneField(User,on_delete=models.CASCADE)


	# additional classes 

	portfolio_site= models.URLField(blank=True)


	profile_pic= models.ImageField(upload_to='profile_pics',blank=True)


	def __str__(self):
		return self.user.username

learning_users/App1/forms.py
from django import forms
from django.contrib.auth.models import User
from App1.models import UserProfileInfo

class UserForm(forms.ModelForm):
	password = forms.CharField(widget= forms.PasswordInput())


	class Meta():
		model=User
		fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
	class Meta():
		model=  UserProfileInfo
		fields =('portfolio_site','profile_pic') 

learning_users/App1/views.py
from django.shortcuts import render
from App1.forms import UserForm,UserProfileInfoForm


from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
	return render(request,'App1/index.html')

@login_required
def special(request):
	return HttpResponse("You are logged in")

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('index'))


def register(request):

	registered= False


	if request.method =="POST":
		user_form= UserForm(data=request.POST)
		profile_form= UserProfileInfoForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():

			user=user_form.save()

			user.set_password(user.password)
			user.save()



			profile = profile_form.save(commit=False)
			profile.user = user

			if 'profile_pic' in request.FILES:
				profile.profile_pic = request.FILES['profile_pic']


			profile.save()


			registered= True
		else :
			print(user_form.errors,profile_form.errors)
	
	else:
		user_form = UserForm()
		profile_form= UserProfileInfoForm()


	return render(request,'App1/registration.html',
							{'user_form':user_form,
							 'profile_form':profile_form,
							 'registered':registered})





def user_login(request):

	if request.method=='POST':
		username= request.POST.get('username')
		password = request.POST.get('password')

		user= authenticate(username=username,password=password)


		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect(reverse('index'))


			else:
				return HttpResponse("Account not active!")

		else:
			print("Someone tried to login and failed!")
			print("Username:{} and Password:{}".format(username,password))
			return HttpResponse("Invalid login details supplied")
	else:
		return render(request,'App1/login.html',{})

learning_users/templates/App1/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<ul class="nav navbar-nav">
				<li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
				<li><a class="navbar-link" href="{% url 'admin:index'%}">ADMIN</a></li>
				<li><a class="navbar-link" href="{% url 'App1:register'%}">REGISTER</a></li>
				{% if user.is_authenticated %}
				<li><a href="{% url 'logout'%}" class="navbar-link">Logout</a></li>
				{% else %}
				<li><a class="navbar-link" href="{% url 'App1:user_login'%}">Login</a></li>
				{% endif %}


			</ul>
		</div>		
	</nav>
	
	<div class="container">
	{% block body_block%}
	{% endblock%}
	</div>

</body>
</html>

learning_users/templates/App1/index.html
{% extends "App1/base.html"%}
{% block body_block%}

<div class="jumbotron">
	<h1>Django level Five</h1>
	
</div>
{%endblock%}

learning_users/templates/App1/login.html
{% extends 'App1/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'App1:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

learning_users/templates/App1/registration.html
{% extends 'App1/base.html'%}

{%load staticfiles%}

{% block body_block%}

<div class="jumbotron">
	{%if registered %}
	<h1>Thank you for registering</h1>
	{%else%}
	<h1>Register Here!</h1>
	<h3>Fill out the form:</h3>

	<form  enctype="multipart/form-data" method="post" >
		{% csrf_token%}
		{{ user_form.as_p }}
		{{ profile_form.as_p}}
		<input type="submit" value="Register">
	</form>	
	{%endif%}
{%endblock%}
		

</div>	